// js/data.js

const ELEMENTS = [
    { num: 1, symbol: 'H', name: '水素', group: 1, period: 1, type: 'nonmetal', mass: 1, shells: [1], valence: 1, electronegativity: 2.2, ion: '+1' },
    { num: 2, symbol: 'He', name: 'ヘリウム', group: 18, period: 1, type: 'noble', mass: 4, shells: [2], valence: 0, electronegativity: null, ion: null },
    { num: 3, symbol: 'Li', name: 'リチウム', group: 1, period: 2, type: 'alkali', mass: 7, shells: [2, 1], valence: 1, electronegativity: 0.98, ion: '+1' },
    { num: 4, symbol: 'Be', name: 'ベリリウム', group: 2, period: 2, type: 'alkali-earth', mass: 9, shells: [2, 2], valence: 2, electronegativity: 1.57, ion: '+2' },
    { num: 5, symbol: 'B', name: 'ホウ素', group: 13, period: 2, type: 'metalloid', mass: 11, shells: [2, 3], valence: 3, electronegativity: 2.04, ion: '+3' },
    { num: 6, symbol: 'C', name: '炭素', group: 14, period: 2, type: 'nonmetal', mass: 12, shells: [2, 4], valence: 4, electronegativity: 2.55, ion: null },
    { num: 7, symbol: 'N', name: '窒素', group: 15, period: 2, type: 'nonmetal', mass: 14, shells: [2, 5], valence: 5, electronegativity: 3.04, ion: '-3' },
    { num: 8, symbol: 'O', name: '酸素', group: 16, period: 2, type: 'nonmetal', mass: 16, shells: [2, 6], valence: 6, electronegativity: 3.44, ion: '-2' },
    { num: 9, symbol: 'F', name: 'フッ素', group: 17, period: 2, type: 'halogen', mass: 19, shells: [2, 7], valence: 7, electronegativity: 3.98, ion: '-1' },
    { num: 10, symbol: 'Ne', name: 'ネオン', group: 18, period: 2, type: 'noble', mass: 20, shells: [2, 8], valence: 0, electronegativity: null, ion: null },
    { num: 11, symbol: 'Na', name: 'ナトリウム', group: 1, period: 3, type: 'alkali', mass: 23, shells: [2, 8, 1], valence: 1, electronegativity: 0.93, ion: '+1' },
    { num: 12, symbol: 'Mg', name: 'マグネシウム', group: 2, period: 3, type: 'alkali-earth', mass: 24, shells: [2, 8, 2], valence: 2, electronegativity: 1.31, ion: '+2' },
    { num: 13, symbol: 'Al', name: 'アルミニウム', group: 13, period: 3, type: 'post-transition', mass: 27, shells: [2, 8, 3], valence: 3, electronegativity: 1.61, ion: '+3' },
    { num: 14, symbol: 'Si', name: 'ケイ素', group: 14, period: 3, type: 'metalloid', mass: 28, shells: [2, 8, 4], valence: 4, electronegativity: 1.9, ion: null },
    { num: 15, symbol: 'P', name: 'リン', group: 15, period: 3, type: 'nonmetal', mass: 31, shells: [2, 8, 5], valence: 5, electronegativity: 2.19, ion: '-3' },
    { num: 16, symbol: 'S', name: '硫黄', group: 16, period: 3, type: 'nonmetal', mass: 32, shells: [2, 8, 6], valence: 6, electronegativity: 2.58, ion: '-2' },
    { num: 17, symbol: 'Cl', name: '塩素', group: 17, period: 3, type: 'halogen', mass: 35, shells: [2, 8, 7], valence: 7, electronegativity: 3.16, ion: '-1' },
    { num: 18, symbol: 'Ar', name: 'アルゴン', group: 18, period: 3, type: 'noble', mass: 40, shells: [2, 8, 8], valence: 0, electronegativity: null, ion: null },
    { num: 19, symbol: 'K', name: 'カリウム', group: 1, period: 4, type: 'alkali', mass: 39, shells: [2, 8, 8, 1], valence: 1, electronegativity: 0.82, ion: '+1' },
    { num: 20, symbol: 'Ca', name: 'カルシウム', group: 2, period: 4, type: 'alkali-earth', mass: 40, shells: [2, 8, 8, 2], valence: 2, electronegativity: 1.0, ion: '+2' },
    { num: 21, symbol: 'Sc', name: 'スカンジウム', group: 3, period: 4, type: 'transition', mass: 45, shells: [2, 8, 9, 2], valence: 2, electronegativity: 1.36, ion: '+3' },
    { num: 22, symbol: 'Ti', name: 'チタン', group: 4, period: 4, type: 'transition', mass: 48, shells: [2, 8, 10, 2], valence: 2, electronegativity: 1.54, ion: '+4' },
    { num: 23, symbol: 'V', name: 'バナジウム', group: 5, period: 4, type: 'transition', mass: 51, shells: [2, 8, 11, 2], valence: 2, electronegativity: 1.63, ion: '+5' },
    { num: 24, symbol: 'Cr', name: 'クロム', group: 6, period: 4, type: 'transition', mass: 52, shells: [2, 8, 13, 1], valence: 1, electronegativity: 1.66, ion: '+3' },
    { num: 25, symbol: 'Mn', name: 'マンガン', group: 7, period: 4, type: 'transition', mass: 55, shells: [2, 8, 13, 2], valence: 2, electronegativity: 1.55, ion: '+2' },
    { num: 26, symbol: 'Fe', name: '鉄', group: 8, period: 4, type: 'transition', mass: 56, shells: [2, 8, 14, 2], valence: 2, electronegativity: 1.83, ion: '+2' },
    { num: 27, symbol: 'Co', name: 'コバルト', group: 9, period: 4, type: 'transition', mass: 59, shells: [2, 8, 15, 2], valence: 2, electronegativity: 1.88, ion: '+2' },
    { num: 28, symbol: 'Ni', name: 'ニッケル', group: 10, period: 4, type: 'transition', mass: 59, shells: [2, 8, 16, 2], valence: 2, electronegativity: 1.91, ion: '+2' },
    { num: 29, symbol: 'Cu', name: '銅', group: 11, period: 4, type: 'transition', mass: 64, shells: [2, 8, 18, 1], valence: 1, electronegativity: 1.90, ion: '+2' },
    { num: 30, symbol: 'Zn', name: '亜鉛', group: 12, period: 4, type: 'transition', mass: 65, shells: [2, 8, 18, 2], valence: 2, electronegativity: 1.65, ion: '+2' },
    { num: 31, symbol: 'Ga', name: 'ガリウム', group: 13, period: 4, type: 'post-transition', mass: 70, shells: [2, 8, 18, 3], valence: 3, electronegativity: 1.81, ion: '+3' },
    { num: 32, symbol: 'Ge', name: 'ゲルマニウム', group: 14, period: 4, type: 'metalloid', mass: 73, shells: [2, 8, 18, 4], valence: 4, electronegativity: 2.01, ion: null },
    { num: 33, symbol: 'As', name: 'ヒ素', group: 15, period: 4, type: 'metalloid', mass: 75, shells: [2, 8, 18, 5], valence: 5, electronegativity: 2.18, ion: '-3' },
    { num: 34, symbol: 'Se', name: 'セレン', group: 16, period: 4, type: 'nonmetal', mass: 79, shells: [2, 8, 18, 6], valence: 6, electronegativity: 2.55, ion: '-2' },
    { num: 35, symbol: 'Br', name: '臭素', group: 17, period: 4, type: 'halogen', mass: 80, shells: [2, 8, 18, 7], valence: 7, electronegativity: 2.96, ion: '-1' },
    { num: 36, symbol: 'Kr', name: 'クリプトン', group: 18, period: 4, type: 'noble', mass: 84, shells: [2, 8, 18, 8], valence: 0, electronegativity: null, ion: null }
];

const MASCOT_MESSAGES = {
    home: "ようこそなのだ！左のメニューから好きなシミュレーションを選ぶのだ！",
    viewer3d: "原子は中心に原子核、周りを電子が飛んでいるのだ！ドラッグして視点を変えられるのだ！",
    isotope: "同位体は重さ（中性子の数）だけが違うクローンなのだ！",
    radiation: "不安定な原子はビーム（放射線）を出して別の原子に変身するのだ！",
    bohr: "電子くんたちのマンション事情なのだ！内側（K殻）から順番に入るのだ！",
    ion: "満室（閉殻）になりたくて電子を捨てたりもらったりしてイオンになるのだ！",
    ionization: "電子をマウスでドラッグして引きはがすのだ！左下の原子ほどチョロいのだ！",
    affinity: "電子を原子に近づけて合体させるのだ！右上の原子ほど引力が強いのだ！",
    electronegativity: "原子同士の電子の綱引きバトルなのだ！右上のヤツが強いのだ！",
    size: "周期表の下に行くほど大きくなるのだ！陽イオンは小さく、陰イオンは大きくなるのだ！",
    periodic: "元素の地図「周期表」なのだ！カードをドラッグして正しい場所に置くのだ！"
};
